melexis/warnings-plugin

.gitignore, setup.py, src/mlx/warnings.py
=> Min threshold

setup.py, src/mlx/warnings.py, tests/test_sphinx.py
=> Fixed regex to also accept warnings without a valid line number

setup.py
=> Fix license in packaging

CONTRIBUTING.md, MANIFEST.in, docs/contributing.rst, setup.py, src/mlx/warnings.py, tox.ini
Since we want external contributions we should have the contribution guide. This should provide a boost to new developers and speed everything up.
=> Create Contribution guide

README.rst
Readme was made richer with Installation, Usage, Issues and Contribution topics. 
Added also Travis and CodeCov badges to README to boost visibility.
=> Adding some more content to README

README.rst, docs/installation.rst, setup.py
Bumping a version in preparation for new release.
Since rst docs are produced, we need to start adding some more
information to them.
=> Adding requirements badge and a bit more installation information

src/mlx/warnings.py
Sanity  check on min-max limits
=> Minimum limit should be zero by default

.travis.yml, docs/conf.py, docs/design.rst, docs/index.rst, docs/requirements.txt, src/mlx/warnings.py, tests/test_doxygen.py, tests/test_junit.py, tests/test_limits.py, tests/test_sphinx.py, tests/test_warnings.py, tox.ini
Minor refactoring so that now we use classes for each checker in one overlay class. That overlay class also needs to include some decision making so that we are able to simply call everything from there.
Closes #19
=> Refactoring for the future

README.rst, docs/conf.py
New tool in block and we can use it. Found a nice discrepancy with print compatibility so it deserves an addition
=> Codeclimate integration

README.rst, src/mlx/warnings.py, tests/test_limits.py
=> Fix issue #23: return number of warnings counted when not within limits

.travis.yml, tox.ini
Filtering coverage to valid files
=> Trying to output code coverage by CodeClimate plugin

docs/design.rst, setup.py, src/mlx/warnings.py, tests/junit_double_fail.xml, tests/junit_no_fail.xml, tests/junit_single_fail.xml, tests/test_junit.py, tests/test_warnings.py, tox.ini
=> fix #20 use parser module for junit failures

src/mlx/warnings.py
This merge request makes sure that wildcards can also be used as arguments for the python script in case it is run on windows.
=> Added glob wildcard expansion

docs/authors.rst, docs/design.rst, src/mlx/warnings.py, tests/junit_double_fail.xml, tests/junit_no_fail.xml, tests/junit_single_fail.xml, tests/test_doxygen.py, tests/test_junit.py, tests/test_sphinx.py
Verbosity needs to summarize the found warnings to the terminal
=> Add verbose flag

src/mlx/warnings.py, tests/test_integration.py
contributing to #41 
also instrumented the code for testing main()
=> Integration test start: JUnit

docs/design.rst, src/mlx/warnings.py, tests/test_junit.py
=> Issue 42: convention about string format

src/mlx/warnings.py, tests/test_sphinx.py
=> Optional line number for sphinx parser

.codeclimate.yml, src/mlx/warnings.py, src/mlx/warnings_checker.py
We need to drop some of the warnings from codeclimate to reduce our technical debt. This is the first step.
=> Minor refactor

src/mlx/warnings.py, tests/test_doxygen.py, tests/test_junit.py, tests/test_limits.py, tests/test_sphinx.py, tests/test_warnings.py
Since init function is not really scale-able this is minior refactor which should solve this
=> Refactor initialization function

.travis.yml, tox.ini
We want a more decently readable documentation which we actually build
already for ages.
Resolves #69
=> Publish the docs to the gh-pages

.travis.yml, README.rst, docs/conf.py, setup.py, src/mlx/warnings.py, src/mlx/warnings_checker.py, tox.ini
=> Drop support for Python 2

README.rst
https://bestpractices.coreinfrastructure.org/en/projects/4368
=> Add CII Best Practices badge

setup.py, src/mlx/junit_checker.py, tests/test_in/robot_version_5.xml, tests/test_robot.py
=> Support Robot Framework 5.x

.github/workflows/python-package.yml, README.rst, docs/requirements.txt, setup.py, src/mlx/warnings.py, tests/test_config.py, tests/test_in/config_example_exclude.yml, tox.ini
=> Support YAML syntax for the configuration file

src/mlx/regex_checker.py
Just some minor tweaks, the behavior remains unchanged. All regular expressions seem to be working as intended.
Closes #38
=> Tweak regular expressions

src/mlx/warnings/warnings.py
=> Warn about ignored keyword arguments

.github/workflows/python-package.yml, setup.py
=> Fix editable build

README.rst
Clarify documentation for the feature introduced in https://github.com/melexis/warnings-plugin/pull/147
I tweaked the wording and important information with regards to the configuration.
=> Clarify documentation about Coverity checker

src/mlx/warnings/polyspace_checker.py, tests/test_in/polyspace_code_quality.json, tests/test_in/polyspace_code_quality_exclude.json
https://docs.gitlab.com/ee/ci/testing/code_quality_troubleshooting.html#no-code-quality-appears-on-merge-requests-when-using-custom-tool
=> FIX: Line properties in Code Quality report for PolyspaceChecker shall be integers

CONTRIBUTING.md
Just in case everyone doesn't know how to behave.
=> Add Code of Conduct

.github/workflows/python-package.yml, README.rst, docs/conf.py, tox.ini
Avoid redirects and fix failing `sphinx-build -b linkcheck` in [CI job](https://github.com/melexis/warnings-plugin/actions/runs/12330848724/job/34416778292?pr=164#step:6:175).
=> Update hyperlinks in README

.github/workflows/python-package.yml, tox.ini
reverting bad changes from https://github.com/melexis/warnings-plugin/pull/161
=> Require build package again to fix release
