- README.rst
- src/mlx/warnings.py
- tests/test_junit.py
Counts number of failures in a JUnit xml file
note: the counting using regex is a bit different from the one above, as multiple failures can be on one line in a single line xml-file. We might want to change the regex statement for doxy/sphinx as well?
note: also made the --doxygen --sphinx options non exclusive... (elif --> if)
> JUnit failures counter

- .codeclimate.yml
- MANIFEST.in
That is because they are not checking the issued marked as invalid and
we have lower score because of that. Current adjustment makes the
duplication detection limit higher, but that will also mean that it will
catch less errors. Once the issue on their side is fixed, we can again
move back to defaults.
> CodeClimate configuration needs to be adjusted

- src/mlx/warnings.py
Code climate reported some duplicate code in the constructors of DoxygenChecker and SphinxChecker. The constructors are indeed not needed as shown in this MR.
> Implicit members for name and pattern, can be overriden

- setup.py
- src/mlx/warnings.py
- tox.ini
setuptools_scm is a good tool where you package one item per repo, so
you do not need to add commits when you want to release, but simply
change the tag in git and version will change by itself. It also takes
nicely care of the development versions with the `hash` and `dev`
attached to the name
> Adding automated version from repo's git tags

- README.rst
- src/mlx/warnings.py
- tests/sphinx_double_warning.txt
- tests/sphinx_single_warning.txt
- tests/test_integration.py
- tox.ini
Since tox does not like pipes and stuff we need to adjust plugin so that you do not have to deal with logs. This allows us to execute the command, parse stdout for errors (and print it), parse stderr for errors (and print it), which eliminates the need for any log files whatsoever.
One of the side effects of this is that stdout and stderr are not aligned in logs (stderr is printed first, stdout second), but implementation where we print out live the data line by line is a bit more complicated.
This closes #3
> Add automatic parsing of the stream

- .travis.yml
We can not force setuptools_scm env variable just for this one deployment. We would need to set variable just in the deploy command of the test-pypi as discussed in https://github.com/pypa/setuptools_scm/issues/217 , but that is not possible as deploy does not take `env`, `before_deploy`,`before_script` commands at all. That is already a feature request for travis-ci https://github.com/travis-ci/travis-ci/issues/6532 and since I would not like to loose any more time I will just remove deployment to test-pypi. 
If someone has an option to fix this while keeping automatic versioning of setuptools_scm, we can always re-add.
> Remove deployment to test.pypi

- src/mlx/warnings.py
- tests/test_integration.py
This is a bugfix for #55 where we did not respect the return value of the command by default. This meant we still parsed for warnings and made our decision on that, even though the command has failed. Now by default we abide the return value of the command but we still add a flag to ignore it. Ignore currently just ignores it, but we might have a better "worse case" ignore, where it would be ignored if there is no output on either stderr or stdout, but otherwise it would still be passing through the checks.
Closes #55
> Respect executed command return value

- src/mlx/warnings.py
- tests/test_integration.py
Windows wildcard expansion resulted in us parsing empty files and returning success (0) with that.
Closes #54
> Open file check

- .travis.yml
- README.rst
- src/mlx/warnings.py
- src/mlx/warnings_checker.py
- tests/config_example.json
- tests/test_config.py
- tests/test_integration.py
- tests/test_xmlrunner.py
Test reports from xmlrunner claim there are no errors or warnings, yet on output it writes them as errors (rightly so). We want to deploy warnings plugin to detect them and fail the build.
This PR has implemented simple regex for ERRORS of the tests from xmlrunner in Python (unittest).
> Python xmlrunner parser

- README.rst
One thing was missed by previous MR.
> Adding xmlrunner to README example configuration

- .gitignore
- src/mlx/warnings.py
- src/mlx/warnings_checker.py
It seems like some flake warnings managed to slip by the CI. Meanwhile I also added to ignore any possible changes to dummy version file which is now overwritten when tox does the packaging and we do not want this to affect us.
> Fixing flake warnings

- README.rst
- src/mlx/warnings.py
- src/mlx/warnings_checker.py
- tests/coverity_single_defect.txt
- tests/test_coverity.py
- tests/test_integration.py
The output is produced with following command:
```
cov-run-desktop --text-output-style=oneline `git diff --name-only --ignore-submodules master`
```
Closes #47
> Initial solution for Coverity regex checker

- .travis.yml
- docs/conf.py
- src/mlx/warnings.py
- src/mlx/warnings_checker.py
- tests/test_config.py
- A bunch of Pylint style fixes
- Import `errno` module where needed and replace `os.errno`, which doesn't exist. 
- Install plantuml in Travis CI.
Closes #45
> Import errno, and style fixes

- .travis.yml
- src/mlx/warnings_checker.py
- tests/test_sphinx.py
Needed for https://github.com/melexis/sphinx-traceability-extension/pull/140
> Include Sphinx warnings without docname (e.g. from mlx.traceability)

- README.rst
- src/mlx/warnings.py
- src/mlx/warnings_checker.py
- tests/sphinx_double_deprecation_warning.txt
- tests/test_config.py
- tests/test_integration.py
- tests/test_sphinx.py
The default behavior changes to no longer exclude Sphinx deprecation warnings. 
Using the new flag `--include-sphinx-deprecation` lets the sphinx checker count warnings that match regex `RemovedInSphinx\\d+Warning`.
This feature was suggested in #84 .
> Add flag to exclude Sphinx deprecation warnings

- MANIFEST.in
- README.rst
- setup.py
- src/mlx/__warnings_version__.py
- src/mlx/warnings.py
- tox.ini
I don't see a usecase for using the plugin without package installation. By not tracking the version file we can have a clean `git status` after local installation with `pip3 install -e .`.
> Add documentation badge and untrack version file

- README.rst
- src/mlx/warnings.py
- src/mlx/warnings_checker.py
- tests/test_integration.py
Example: Instead of using both `--minwarnings 2` and `--maxwarnings 2` you can now use `--exact-warnings 2` to require exactly 2 warnings to be counted for the script to return 0 (success) .
Note: input arguments `--min-warnings` and `--max-warnings` (hyphenated) are now valid.
Closes #87
> Single option to require an exact amount of warnings to be counted

- README.rst
- src/mlx/warnings.py
- src/mlx/warnings_checker.py
- tests/sphinx_traceability_output.txt
- tests/test_integration.py
Since tag 0.8.0 (https://github.com/melexis/warnings-plugin/commit/a32f4ebbccb811de9001af8a7f642d2cac96b228) there has been an unwanted behavior of the plugin where it can return 0 on failure. 
Let's return 1 instead of 0 if the number of warnings is 0, but we expected more than 0 warnings. 
For example, we don't want the plugin to return 0 when there are 0 warnings counted and we use `--minwarnings 1`.
> Never return 0 on failure

- src/mlx/warnings_checker.py
Fixed printed explanation about error code when the number of warnings exceeds the maximum limit.
Example of error: when the minimum limit is set to 0 and the maximum limit set to 1, the plugin prints the following when it has counted 2 warnings:
`Number of warnings (2) is higher than the maximum limit (0). Returning error code 2.`
The correct explanation is:
`Number of warnings (2) is higher than the maximum limit (1). Returning error code 2.`
Bug created in https://github.com/melexis/warnings-plugin/pull/89 (version 1.3.0).
> Fix error message when maximum limit is exceeded

- README.rst
- src/mlx/junit_checker.py
- src/mlx/robot_checker.py
- src/mlx/warnings.py
- tests/test_in/config_example_robot.json
- tests/test_in/config_example_robot_invalid_suite.json
- tests/test_integration.py
Verify that the value of the `--name` input argument (only useful in combination with `--robot`) exists in the input file (xUnit XML file). If the given suite name does not exist, an error message is printed and error code -1 is returned.
Since this behavior may be undesired when using a `--config` file, this feature can be explicitly disabled by setting a new, optional setting called `"check_suite_names"` to `false` as shown below:
```
{
"robot": {
"enabled": true,
"check_suite_names": false,
"suites": [
{
"name": "My Suite Name",
"min": 0,
"max": 0
}
}
}
```
The default behavior is to raise an error when a suite name is not present in the input file, both for `--name` and `--config`.
> Verify the presence of the robot suite name

- docs/installation.rst
- setup.py
- src/mlx/junit_checker.py
Drop lxml as dependency by using the built-in xml module instead. If there are errors while parsing an input XML file, e.g. due to invalid syntax, the description of the error may differ.
> Drop lxml as dependency

- README.rst
- src/mlx/junit_checker.py
- src/mlx/regex_checker.py
- src/mlx/robot_checker.py
- src/mlx/warnings_checker.py
- tests/test_config.py
- tests/test_robot.py
The feature that lets you exclude matches by configuring regexes is not yet supported for robot and junit checkers. See [readme](https://melexis.github.io/warnings-plugin/readme.html#exclude-matches-with-regexes). This PR adds support for this feature to those two checkers so that all checkers support this feature.
> Support exclude feature for robot and junit checkers

- setup.py
- tox.ini
Changes in junitparser==2.0.0b1: https://github.com/weiwei/junitparser/commit/e1270ebd18e9a64d8468525f445b5dbbe9e38b53
Let's look to support this version in the future. For now, we should release this restriction asap. I opened https://github.com/melexis/warnings-plugin/issues/109 to follow up.
> Restrict max version of junitparser as version 2.0.0 is incompatible

- src/mlx/warnings/regex_checker.py
- tests/test_integration.py
The Code Quality report expects a relative path. If the warnings plugin is executed in a different location than the tools that generate the warnings/errors, it might not be able to convert the absolute path to a relative path and raise a `ValueError`.
https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool
> Clarify failure reason when absolute path cannot be converted for Code Quality report

- README.rst
- src/mlx/warnings/polyspace_checker.py
- src/mlx/warnings/robot_checker.py
- src/mlx/warnings/warnings.py
- src/mlx/warnings/warnings_checker.py
- tests/test_in/config_example_polyspace_exclude.json
- tests/test_in/config_example_robot.json
- tests/test_in/polyspace.tsv
- tests/test_in/polyspace_code_quality.json
- tests/test_in/polyspace_code_quality_exclude.json
- tests/test_integration.py
- tests/test_polyspace.py
- Exclude Polyspace defects with a status "Not a Defect" or "Justified"
- Make it possible to use environment variables for `min` and `max` keys instead of numbers
> Exclude Polyspace defects with status "Not a Defect" or "Justified"; Add substitution of env variables for min/max possible for Robot and Polyspace

- README.rst
- src/mlx/warnings/polyspace_checker.py
- src/mlx/warnings/regex_checker.py
- src/mlx/warnings/warnings.py
- src/mlx/warnings/warnings_checker.py
- tests/test_in/config_example.json
- tests/test_in/mixed_warnings.txt
Use a detailed configuration for counting different classifications, for example:
```
"coverity": {
"enabled": true,
"intentional": {
"min": 0,
"max": "-1"
},
"bug": {
"max": 0
},
"pending": {
"min": 0,
"max": 0
},
"false_positive": {
"max": -1
}
```
`-1` represents `math.inf` what can be seen as "do not count". This can only be used for `max` and can also be used in other checkers.
> Add code quality report to CoverityChecker

- src/mlx/warnings/polyspace_checker.py
- src/mlx/warnings/regex_checker.py
- src/mlx/warnings/robot_checker.py
- src/mlx/warnings/warnings.py
- src/mlx/warnings/warnings_checker.py
- tests/test_coverity.py
- tests/test_in/code_quality.json
- tests/test_in/code_quality_format.json
- tests/test_in/config_example_coverity.yml
- tests/test_in/coverity_cq.json
- tests/test_in/defects.txt
- tox.ini
Code quality report is missing Coverity defects when the classification is not configured in the configuration file.
If `--coverity` is used without specifying a configuration file, the code quality report is always empty as a result. This behavior is not desired.
`cq_findings` is from now on a property that can be overwritten and extended with `cq_findings` of all sub-checkers instead of sharing the list object with sub-checkers, which is prone to error because one can forget to share the object.
> Fix code quality bug due missing shared object

- src/mlx/warnings/__main__.py
- src/mlx/warnings/exceptions.py
- src/mlx/warnings/junit_checker.py
- src/mlx/warnings/polyspace_checker.py
- src/mlx/warnings/regex_checker.py
- src/mlx/warnings/robot_checker.py
- src/mlx/warnings/warnings.py
- src/mlx/warnings/warnings_checker.py
One of the Best practices is to us SPDX identifiers for your source files to present  license file. I have added it to all the packaged source files, as that is what is delivered to the customer.
https://spdx.dev/learn/handling-license-info/#how
As a side action I added coding stuff to the `__main__.py` which did not have it before, but it had `python entrypoint`
> Add SPDX identifier to all the source files

- .github/workflows/python-package.yml
- README.rst
- setup.cfg
- src/mlx/warnings/regex_checker.py
- tests/test_coverity.py
- tests/test_in/code_quality.json
- tests/test_in/code_quality_format.json
- tests/test_in/config_cq_description_format.json
- tests/test_in/config_example.json
- tests/test_in/config_example_coverity.yml
- tests/test_in/coverity_cq.json
- tests/test_in/coverity_full.txt
- tests/test_in/defects.txt
- tests/test_in/mixed_warnings.txt
- tox.ini
It was impossible to configure the tool to include the CID of Coverity defects in the Code Quality report. This is very useful information, however, so I decided to include it by default.
Treating this as a bug fix for release [5.5.0](https://github.com/melexis/warnings-plugin/releases/tag/5.5.0)
> Include CID of Coverity defects in CQ report

- src/mlx/warnings/code_quality.py
- src/mlx/warnings/polyspace_checker.py
- tests/test_in/polyspace.tsv
- tests/test_in/polyspace_code_quality.json
- tests/test_in/polyspace_code_quality_exclude.json
- Accept the line and column values of the Polyspace's input to be 0. When the line or column is 0, the line or column in the finding will be 1. Fixes this kind of errors: `ValueError: Expected column number greater than 0; Got 0`
- line or column values defaults to 1, also when the value can't be converted to an integer
> More robust Code Quality reports for PolyspaceChecker

- src/mlx/warnings/code_quality.py
- src/mlx/warnings/warnings.py
- tests/test_in/polyspace.tsv
- tests/test_in/polyspace_code_quality.json
- tests/test_in/polyspace_code_quality_exclude.json
Issue
=====
Polyspace uses `/?extern` for example as file in some cases.
This results in a ValueError when creating code quality reports, which is not intended.
```
ValueError: Failed to convert abolute path to relative path for Code Quality report: '/?extern' is not in the subpath of '/some/other/path' OR one path is relative and the other is absolute.
```
Fix
===
When the path of the file starts with `/?` it will strip these characters and the rest of the text will be the path of that specific finding in the code quality report.
Example: `/?extern` will result in `extern`
> FIX: ValueError when treating location info  '/?extern' as an absolute path

- CONTRIBUTING.md
- README.rst
- docs/conf.py
- src/mlx/warnings/junit_checker.py
- tests/test_in/robot_double_nested_suite.xml
- tests/test_in/robot_nested_suite.xml
- tests/test_integration.py
- tests/test_robot.py
The Robot Framework XML parser now correctly traverses all nested test suites. The previous implementation only supported up to two levels of nested suites. This change allows the warnings plugin to identify and report failures in test cases that are located within any number of nested suites.
To verify this, some new test cases have been added.
> Traverse nested Robot test suites.

- src/mlx/warnings/regex_checker.py
Sphinx has introduced ANSI color escape codes to the warnings to color them red. As a result, the tool can't match warnings when an ANSI color code is present (without filename).
To fix this issue, every ANSI color escape code is removed from the content.
> Remove ANSI color escape codes from content

- README.rst
`min` and `max` are required keys in the configuration file, otherwise it will raise an error like:
`mlx.warnings.exceptions.WarningsConfigError: Incomplete config. Missing: 'min'`
> Fix README by adding the required `min` key to Coverity checker example
